### ISSUE TITLE
NHP vs Human Toggle

### ISSUE THREAD

**Issue by ostanley** [afids/afids-validator#109]
## The problem

To be clearer to the end user and ensure the database stays clean we need to ask the user if the data they are uploading is NHP or human. This can be done in a toggle or dropdown. Mixing organism and template should result in a warning. 

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md)_

**Comment by kaitj** [comment]
Addressed by #129 - using a dynamic dropdown to future proof for more species.
