### ISSUE TITLE
Tweak UI

### ISSUE THREAD

**Issue by tkkuehn** [afids/afids-validator#127]
## The problem

- [x] The Validator page says "Select the AFIDs FCSV to validate." This should be updated to read something like "Select the AFIDs file to validate."
- [x] The width of the UI elements on the validator page are inconsistent -- The dropdown is long (but not the full width of the section), while some of the text is narrower. Remember to check the results page too as this is addressed.
- [x] On short pages, the footer "floats" up to the end of the content instead of staying at the bottom of the page.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md)_

**Comment by kaitj** [comment]
Thanks @tkkuehn - I've just modified the issue to use checkboxes so that we can check off as thigns get fixed.

**Comment by kaitj** [comment]
* "AFIDs FCSV" fixed in 641ce0e 
* Footer wrapped in d878be6
