### ISSUE TITLE
Migrate AFIDs Validator to Graham Cloud

### ISSUE THREAD

**Issue by tkkuehn** [afids/afids-validator#175]
The AFIDs Validator is currently running on Heroku, which imposes some management overhead that isn't totally necessary. It would be good to migrate it to Graham Cloud so we have more control over the kind of resources it's granted and so that it's easier to add integrations with other AFIDs projects like AFIDs-Auto.

Steps:
- Set up an instance to handle this (on whichever allocation is best).
- Install prerequisite system packages (Python).
- Install a web server (nginx? apache?).
- Set up a database (Postgres?).
- Install the validator itself.
- Initialize everything.
- Optionally, set up a custom domain name.
- Optionally, set up HTTPS with LetsEncrypt.
- Optionally, repeat all of the above for a test environment.

**Comment by kaitj** [comment]
I think this is done? Would be good to discuss during the meeting to talk about anything else that needs to be done.

**Comment by tkkuehn** [comment]
I'd say this is fully done now, with the addition of a test environment still possible in the future.
