### ISSUE TITLE
Stop using FLASK_ENV

### ISSUE THREAD

**Issue by tkkuehn** [afids/afids-validator#204]
## The problem

The FLASK_ENV config variable is deprecated in favour of FLASK_DEBUG (according to startup logs). We need to look into this and refactor the config code accordingly.

**Comment by kaitj** [comment]
Took a dive into this - we make set the `FLASK_ENV` variable to define the environment we are in, however we use the appropriate `DEBUG` and `TESTING` variables for configuration. 

While Flask may have changed this, I think for configuration purposes, making use of FLASK_ENV is still easiest for a contributor to change between the different environments with the code handling all of the necessary configuration. 

The code will be refactored a little bit to make it more concise, but I think this ends up being a non-issue for us. We can revisit this in the future if this is something we want to change.
