### ISSUE TITLE
Fix README banner

### ISSUE THREAD

**Issue by kaitj** [afids/afids-validator#226]
## The problem

As a result of the frontend changes, the URL to the banner is currently broken. This should be resolved by pointing the image to the correct location in the repository.

## Environment

* Browser (with version)
* Dropdown menu option
* File uploaded (if applicable)

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md)_

**Comment by LaThanhTrong** [comment]
Can I work on this issuse?
