### ISSUE TITLE
Validator Logic (Do you mean section?)

### ISSUE THREAD

**Issue by ostanley** [afids/afids-validator#27]
We want the validator to fail completely in some cases and partially in others.

Completely:
incorrect # of fiducials
Some tolerance failure if X partial failures, fail completely (~25%)
misordering of the fiducials inside the files

Partially:
Incorrect capitalization
Incorrect spelling
L-R fiducial

When throwing a complete failure still throw out as many errors as possible.
Any thoughts @jclauneuro @tkkuehn

**Comment by kaitj** [comment]
Had an additional thought and it might just be a temporary workaround to the issues we are currently having. Could we write the validations to assume that the templates are always correct (ie. it doesn't actually check the templates) and only looks at the user submitted fiducials?

**Comment by ostanley** [comment]
Then how would it compare the names? Just from our list? Long term I think
it should maybe get the list from the template itself but short term this
seems like a good option.

**Comment by kaitj** [comment]
The names are being compared to a hard-coded list (I believe). I think that was a result of the fiducial names being static so the comparison will still happen for the submitted fiducials. The assumption would be that the fiducials are in the correct order in the template and even if the naming is wrong, the fiducial coordinates are still correct.

**Comment by tkkuehn** [comment]
(Sorry for the wall of text here, I started writing my thoughts and they ballooned)

I think it's worth discussing what we precisely mean by failing completely vs. partially.

I agree that the most valuable behaviour would be to communicate as many failures as possible - the sticking point just seems to be at what point we stop trying to parse the file.

It seems to me that there are two major steps: first, we want to make sure that the fcsv is formatted properly, then we want to see if there are any problems with the fiducial placements.

Starting with the fcsv formatting, we can start by looking at the fcsv format and take note of any problems but then keep going.

I think a reasonable approach would be to read the first (up to) 32 rows in the fcsv, and check for each of the following issues in each row:

1. Does the row have the right number of fields?
    - This makes interpreting the fields kind of a crapshoot because we don't know for sure which fields are missing, where fields were added, or if the fields we need are there at all
    - We could try to look at the indices where we normally expect the fields we care about to be, but I think this is a big enough problem that we should just stop trying to parse the row here in this case
2. Is the `label` correct?
    - Could either not be an integer, or the incorrect integer based on the index of the row we're looking at
    - We can keep going in this case, but it definitely makes the fcsv invalid
    - If the label isn't an integer, we can't check its correspondence with the row's `desc`
3. Is the `desc` known?
    - Could be a known `desc` with incorrect capitalization, which we should report but doesn't stop us from any further validation
    - Could also be a totally unrecognized `desc`, which means we can't check its correspondence with the row's `label` and the fcsv is invalid
4. Do the row's `label` and `desc` match?
    - Can't check if 2 or 3 fails
    - If not, the fcsv is invalid
5. Are the values of `x`, `y`, and `z` valid?
    - Could be infinite or not a number that can be parsed, either one of which means the fcsv is invalid.

If after this process we find that there are not exactly 32 rows, we should report that as well and stop here. We can also report which fiducials we didn't find. If any of the above issues are present, we should stop here and report all the problems.

If no major formatting issues were found, we know the fcsv is at least formatted properly. Now we can move on to analyzing the fiducial locations, checking for the following issue:

1. Are any L-R fiducials likely reversed, based on their locations in the reference template?

I don't know of any other fiducial placement errors we can check for automatically, but if there were we could do that at this point, then finish and report any we find or conclude that the fcsv is valid and show the distance metrics.

Let me know if this makes sense and if there's anything to add or think about differently!

**Comment by tkkuehn** [comment]
> I'm not sure if [the number of fields] is something we would need to check as the fcsv is generated through Slicer, which I think populates all of the required fields. This may be somethign we should check by trying to generate an empty fcsv file. The only way columns would be lost is this is done manually after the it was saved from Slicer.

I think this is a way of handling text files that just aren't (f)csvs at all and got uploaded for whatever reason, which it would probably be good to be prepared for. On that note, we should probably make sure the system handles non-text files gracefully.

> [Re: 4] If 2 fails, it should just be a complete failure anyways I think (see point above). If 3 fails, it can be an error message/warning.

It should be noted that it's possible for both 2 and 3 to succeed and this one to fail (although we could just roll it into 3 conceptually).

Everything else you said sounds reasonable to me!

**Comment by kaitj** [comment]
With capitalization not being important at this stage, should we leave out the "Incorrect capitalization" as a partial failure then?

**Comment by ostanley** [comment]
I think so. It doesn't make sense if we aren't enforcing it on our end.

**Comment by kaitj** [comment]
With fiducial subsets in mind (#74) along with other features implemented, is this still something we need to worry about? Most of the initial errors / warnings have either been implemented or is no longer relevant (ie. misordering of fiducials).

**Comment by kaitj** [comment]
Closing this issue. Most recent implementation seem to address or make some of the concerns irrelevant. Can revisit this later if there are certain things we want to address.
