### ISSUE TITLE
Visualization / Stats

### ISSUE THREAD

**Issue by Park-Patrick** [afids/afids-validator#28]
Histogram of errors
- Histogram of errors in relation to cartesian coordinates (i.e. bias)
- subplots?
- mean squared error (are you doing better in certain sections? left vs right)
- top 3 best / worst?

**Comment by kaitj** [comment]
Visualization prioritized for June 2020 completion

**Comment by kaitj** [comment]
This seems redundant with #69 with both focused on the visualization implementation

@tkkuehn thoughts?

**Comment by kaitj** [comment]
See #69 for up to date visualization. Closing
