### ISSUE TITLE
dataset comparison and outlier detection

### ISSUE THREAD

**Issue by Park-Patrick** [afids/afids-validator#50]
Assuming anatomical similarities between subjects (which most of the points are?), could be used to evaluate registration.

Otherwise if fiducial placement + registration is assumed reliable, could be used as coarse measure of anatomical differences between groups (i.e. patients vs controls)

**Comment by kaitj** [comment]
Outliers while not explicitly warning the user, will be shown in the visualization.

Group differences seem to be out of scope for validator purposes.

Closing issue!
