### ISSUE TITLE
OHBM hackathon ideas

### ISSUE THREAD

**Issue by jclauneuro** [afids/afids-validator#60]
Inspired by @kaitj's resolution to clean up the code over the coming months. Just wanted to open an issue to explore how we might try to engage the greater OHBM community at the upcoming meeting in Montreal.

Perhaps ideas for either tutorials ("train track") and/or extensions to the current AFIDs-validator workflow.

**Comment by kaitj** [comment]
On the development side, the brainhack would be a great place to get some feedback and help for implementing some of the new features. 

Would be good for the traintrack too (they are taking suggestions!) / way to implement a new template?

**Comment by jclauneuro** [comment]
Great idea to propose an AFIDs tutorial at the traintrack -- and I like the idea of getting users to implement / place AFIDs on new templates that are being used by the community (the HCP template for example).

**Comment by tkkuehn** [comment]
The OHBM hackathon in question has now come and gone, so I'm going to close this.
