### ISSUE TITLE
manage traffic / uploads

### ISSUE THREAD

**Issue by Park-Patrick** [afids/afids-validator#62]
- [x] Change data upload to db as opt-in checkbox (to prevent being flooded with nonsense entries)

- [x] Someone who chooses not to upload should still be able to see metrics / visualization (temp entry?)

- [x] This could also be a good place to categorize traffic, i.e. (Is this your first time using the afids protocol)

Thoughts? @tkkuehn and others

**Comment by kaitj** [comment]
- Table is still shown to user (metrics)
- Traffic categorized to an extent by future unique ID implementation

Closing issue
