### ISSUE TITLE
Landing Page Intro

### ISSUE THREAD

**Issue by kaitj** [afids/afids-validator#64]
Write up for landing page + pictures/video/demo, etc.

**Comment by kaitj** [comment]
We have a short description up now thanks to @tkkuehn that will be merged in with #63 so that we can go live with the new template. 

Could always add more details to it though and formalize it a little more @ggupta23.

**Comment by jclauneuro** [comment]
Provide video to @kaitj for landing page

**Comment by jclauneuro** [comment]
Just provided the video to @kaitj.

**Comment by kaitj** [comment]
Video was added in an open PR #77.

**Comment by kaitj** [comment]
This is complete, closing!
