### ISSUE TITLE
[Bug] Upload Error

### ISSUE THREAD

**Issue by kaitj** [afids/afids-validator#71]
Upload of fcsv throws error with message below:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Unit test isn't catching error

@tkkuehn - please add log

**Comment by tkkuehn** [comment]
Logs:

**Comment by kaitj** [comment]
Just to add onto this - just tested it out locally. Upload works fine when testing locally.

**Comment by kaitj** [comment]
Turns out no error in the code! Upload test was done using a "fcsv" file that contained html instead of fiducials. 

Results in 500 error.

Issue can be closed. Alternatively, add in error handling in case the contents of the file don't match what is expected for fcsv (ie. html code).

@tkkuehn @Park-Patrick

**Comment by kaitj** [comment]
Error was encountered again at Brainweb. Somethign we discussed yesterday that maybe what we should be doing is chceking the first few lines of the file, and if it does not match what is expected, throw a meaningful error.

Additionally, validator (should not currently) be saving any of the contents of these files if error is encountered as it doesn't get to that stage.

**Comment by kaitj** [comment]
See #79, which addresses the issue of invalid content

**Comment by kaitj** [comment]
PR for checking the invalid content has been merged. There are two checks implemented here:

1. Whether it has a proper header - will throw an error if it does not
2. Whether it has proper contents in case it passes the header check - will throw an error along the lines of invalid row values! 

Thanks @tkkuehn
