### ISSUE TITLE
Add contributions document

### ISSUE THREAD

**Issue by kaitj** [afids/afids-validator#96]
## The problem

Currently repository does not have a contributions document for users who may want to contribute. This would be a useful thing to have.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md)_

**Comment by tkkuehn** [comment]
See https://github.blog/2012-09-17-contributing-guidelines/

**Comment by kaitj** [comment]
Could you add the following to the guide (from the NumPy dev guide): 

```
API: an (incompatible) API change
BENCH: changes to the benchmark suite
BLD: change related to building numpy
BUG: bug fix
DEP: deprecate something, or remove a deprecated object
DEV: development tool or utility
DOC: documentation
ENH: enhancement
MAINT: maintenance commit (refactoring, typos, etc.)
REV: revert an earlier commit
STY: style fix (whitespace, PEP8)
TST: addition or modification of tests
REL: related to releasing numpy
```

**Comment by tkkuehn** [comment]
> ```
> REL: related to releasing numpy
> ```

Note that numpy here should say "the AFIDs Validator" or something instead.

**Comment by kaitj** [comment]
This is now complete! Closing.
