### ISSUE TITLE
AFIDs Class / Internal Representation

### ISSUE THREAD

**Issue by tkkuehn** [afids/afids-validator#98]
## The problem

We currently parse .fcsv files directly into JSON strings. There's not really any good reason to do it this way, and now that Slicer is moving from .fcsv files to .json files, we should have an internal representation that can import from and export to either file format. An AFIDs class seems like a good approach.

**Comment by kaitj** [comment]
Include necessary fields, including coordinate system. One note is that fiducial markups are known as control points.

**Comment by kaitj** [comment]
TODO:

- [ ] AFIDs class
- [ ] fcsv to AFIDs class
- [ ] json to AFIDs class

**Comment by kaitj** [comment]
Adding some quick notes as I work through creating this AFIDs class. I don't think the class retain every field, but rather the necessary ones, as the `.fcsv` and `.json` files have some differences between them, both in how data is retained (e.g. CoordinateSystem) and what fields are called (e.g. "vis" vs "visibility"), while other fields can just be set to some default value.

My current thinking is we have an AFIDs class, which stores the information such as the coordinate system, and we have a tree that stores the fiducial information itself so it can be retained in a single object. As mentioned previously, I'll have a mockup for for the next validator meeting, though I do think we should think of what other fields we may want to include.

With respect to exporting, I am leaning towards creating two separate functions to export to either json or fcsv with some default parameters, though we would need to add that functionality into the validator page. With importing, I think ultimately, the current version of the `fcsv_to_json` will be deprecated and a couple of new functions will be created in its place.

**Comment by kaitj** [comment]
We should update the blurb on the home page of the validator since it specifically mentions `fcsv` files.
